# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa0521752ed5c60a38bf6cb4d48d3e434f2ccf191710f26cf30d02ea9f09889e2d894196254fb9bb956d2b74fb999c94009d138d111b528c9d75faa8b5252e5

test:
  secret_key_base: e0aa7f89f923883ab5be532526365545afeb0b3637a8a16ddaad5d880a5cf6bf4377813c305a603a3eb77a490a361acc2bd2d7de1bfe01fdfe7ce87914140ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
